create database wop;
grant select,insert,update,delete on wop.* to wop@localhost identified by "wop";

DROP TABLE IF EXISTS WOP_USER_INFO
;
CREATE TABLE WOP_USER_INFO
(
	USERID VARCHAR(32) NOT NULL,
	USERNAME VARCHAR(32) NOT NULL,
	PASSWORD VARCHAR(32) NOT NULL,
	NICKNAME VARCHAR(32) ,
	ROLE NUMERIC(1) NOT NULL,
	IMEI VARCHAR(64),
	WWID VARCHAR(32),
	REGISTER_TIME NUMERIC(16) NOT NULL,
	MOBILE VARCHAR(18),
	ADDRESS VARCHAR(64),
	SEX NUMERIC(1) NOT NULL,
	TEL VARCHAR(18),
	MAIL VARCHAR(32),
	QQ VARCHAR(16),
	STATE NUMERIC(2)  NOT NULL,
	PRIMARY KEY (USERID)
) DEFAULT CHARSET=utf8
;
commit;
